# ВАЖНО: Не указывайте spring.profiles.active здесь!
# Вместо этого раскомментируйте строку в application.properties

# Локальная база данных PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/AcademicSupport
spring.datasource.username=postgres
spring.datasource.password=1111

# Логирование для отладки
logging.level.io.github.alexeyaleksandrov.jacademicsupport=DEBUG