name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        env:
          GIGACHAT_TOKEN: ${{ secrets.GIGACHAT_API_TOKEN }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION }}
          # Включаем BuildKit для ускорения сборки
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: GIGACHAT_TOKEN,JWT_SECRET_KEY,JWT_EXPIRATION_TIME,DOCKER_BUILDKIT,COMPOSE_DOCKER_CLI_BUILD
          script: |
            echo "=== Connecting to VPS ==="
            cd /home/JAcademicSupport/
            
            echo "=== Setting up environment variables ==="
            export GIGACHAT_API_TOKEN="$GIGACHAT_TOKEN"
            export JWT_SECRET="$JWT_SECRET_KEY"
            export JWT_EXPIRATION="$JWT_EXPIRATION_TIME"
            
            echo "=== Setting execute permissions ==="
            chmod +x deploy.sh
            echo "Permissions after chmod:"
            ls -la deploy.sh | cut -d ' ' -f 1
            
            echo "=== Checking if deploy.sh is executable ==="
            if [ ! -x deploy.sh ]; then
              echo " ERROR: deploy.sh is not executable after chmod!"
              exit 1
            fi
            
            echo " deploy.sh is executable, proceeding..."
            
            echo "=== Running deploy script ==="
            # 
            if ./deploy.sh; then
              echo " deploy.sh completed successfully"
            else
              echo " deploy.sh failed with exit code $?"
              exit 1
            fi
            
            echo "=== Deployment completed successfully ==="